name: Email Notification on Commit
on: [push]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: New Commit in ONE lab by ${{ github.actor }}
          to: kmranrg@unm.edu
          from: GitHub Actions
          body: A new commit was just pushed to the repository by ${{ github.actor }}. You can check the repository for the latest changes.
